### ISSUE TITLE
Вопрос по работе прибора

### ISSUE THREAD

**Issue by star003** [himikat123/Clock#1]
Нашел пару интересных недостатков. 
1. Если имя сети например ssswifi++ , как у меня на работе - то ++ программа категорически не запоминает. 
2. Кнопка SETTING работает только если часы подсоединены к точке доступа. 
    Если мы их принесли в другое место , то часы настроить практически невозможно, пока не подключатся к известной сети.
3. Если нет интернета то время застывает на одном положении и не считает﻿

**Comment by himikat123** [comment]
Спасибо. 
Все исправил. Код обновил. Смотрите новую схему и плату.
