### ISSUE TITLE
Уходит в бесконечный ребут

### ISSUE THREAD

**Issue by star003** [himikat123/Clock#2]
Пишет вот это 

плата wemos d1 mini

ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld

**Comment by himikat123** [comment]
Проверяйте монтаж и исправность элементов, похоже что у вас плата ESP не выходит из режима обновления прошивки.
